### ISSUE TITLE
Appreciation for "nextcloud-debian-ins.sh" Script

### ISSUE THREAD

**Issue by adoolaard** [nicrame/Linux-Scripts#1]
Hi Marcin,

I wanted to share my gratitude for your "nextcloud-debian-ins.sh" script. It has made setting up Nextcloud on Debian a seamless process. I know this isn't an issue, but I wanted to express my thanks. Your contribution is truly valued!

Best regards,
Abel

**Comment by nicrame** [comment]
Thank You! I'm very happy that it's working well, and making life easier.

**Comment by nicrame** [comment]
Thank You! I'm very happy that it's working well, and making life easier.
